apiVersion: apps/v1
kind: Deployment
metadata:
  name: beanleafclassification
spec:
  replicas: 2
  selector:
    matchLabels:
      app: beanleafclassifier
  template:
    metadata:
      labels:
        app: beanleafclassifier
    spec:
      containers:
      - name: beanleaf-classification-app
        image: gcr.io/mlops-poc-337511/beanleaf_classification_app:v1
        ports:
        - containerPort: 8501